# Generated by Django 5.2.17 on 2026-10-08 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bill_scanner.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('company', '0081_remove_company_notes_remove_manufacturerpart_notes_and_more'),
        ('order', '0122_remove_purchaseorder_notes_remove_returnorder_notes_and_more'),
        ('part', '0154_remove_part_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=bill_scanner.models.bill_upload_path,
                        verbose_name='File',
                    ),
                ),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Waiting for extraction'),
                            ('processing', 'Extracting'),
                            ('retry', 'Waiting to retry'),
                            ('failed', 'Extraction failed'),
                            ('review', 'Ready for review'),
                            ('completed', 'Purchase order created'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                (
                    'bill_number',
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    'bill_key',
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('supplier_confidence', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'purchase_order',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='order.purchaseorder',
                    ),
                ),
                (
                    'supplier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='company.company',
                    ),
                ),
            ],
            options={'verbose_name': 'Scanned Bill', 'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='BillAuditLog',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('bill_label', models.CharField(max_length=300)),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('uploaded', 'Uploaded'),
                            ('edited', 'Edited'),
                            ('line_edited', 'Line edited'),
                            ('confirmed', 'Confirmed and received'),
                            ('deleted', 'Deleted'),
                        ],
                        max_length=20,
                    ),
                ),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'bill',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit',
                        to='bill_scanner.bill',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('sku', models.CharField(blank=True, max_length=100)),
                (
                    'quantity',
                    models.DecimalField(decimal_places=5, default=0, max_digits=15),
                ),
                (
                    'unit_price',
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=19, null=True
                    ),
                ),
                ('confidence', models.FloatField(default=0)),
                (
                    'match_method',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('', 'No match'),
                            ('supplier_sku', 'Supplier SKU'),
                            ('sku', 'SKU of another supplier'),
                            ('mpn', 'Manufacturer part number'),
                            ('ipn', 'Internal part number'),
                            ('name', 'Fuzzy name match'),
                            ('manual', 'Chosen by user'),
                        ],
                        default='',
                        max_length=20,
                    ),
                ),
                ('match_confidence', models.FloatField(default=0)),
                ('skip', models.BooleanField(default=False)),
                (
                    'bill',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='bill_scanner.bill',
                    ),
                ),
                (
                    'part',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='part.part',
                    ),
                ),
                (
                    'supplier_part',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='company.supplierpart',
                    ),
                ),
            ],
            options={'ordering': ['bill', 'line_number']},
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'completed')),
                fields=('supplier', 'bill_key'),
                name='bill_scanner_unique_received_bill',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='billline', unique_together={('bill', 'line_number')}
        ),
    ]
